### PR TITLE
WIP: refactor(sdk): Swift contructors workaround

### PR DESCRIPTION
**Pull request by vkubiv**

### CODE REVIEW

**Review by birtony — APPROVED** [review]

**Comment by rolsonquadras** [comment]
Marked this as WIP to avoid merging the PR as we need to better understand if this breaks existing code.

**Review by talwinder50 — COMMENTED** [review]
@vkubiv how does naming look in the binding i believe it will be like custructorNewInteraction ?? aa swift binding append names by itself too

**Comment by vkubiv** [comment]
@talwinder50 like this: `LocalkmsConstructors().newKMS(kmsStore())`

**Comment by DRK3** [comment]
Should we close this PR, or do we still plan on adding it in? Will require a lot of refactoring due to the changes on main since this was opened @vkubiv @rolsonquadras

**Comment by rolsonquadras** [comment]
Lets close this for now @DRK3 @vkubiv - if we need it, we can reopen.

**Pull request closed without merging**
