### PR TITLE
fix(app): (Android) Add P-384 key suppport for did:jwk

### PR DESCRIPTION
**Pull request by rolsonquadras**
The changes were lost during the androind refactoring PR. The orginal PR to add support is https://github.com/trustbloc/wallet-sdk/pull/276/files.

### CODE REVIEW

**Comment by DRK3** [comment]
Typo in commit and PR title `suppprt`

**Review by talwinder50 — APPROVED** [review]

**Comment by talwinder50** [comment]
> Typo in commit and PR title `suppprt`

fixed

**Review by DRK3 — APPROVED** [review]
See my comment regarding the typo. One other minor note - while you're fixing the typo, I'd suggest specifying that this fix is for the Android demo app specifically

**Comment by rolsonquadras** [comment]
> See my comment regarding the typo. One other minor note - while you're fixing the typo, I'd suggest specifying that this fix is for the Android demo app specifically

Done

**Pull request merged**
